apiVersion: v2
name: microservice
description: A Helm chart for deploying microservices
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservices
  - flask
  - python
maintainers:
  - name: Denol007
    email: denol007@github.com
