# Helm values for user-service

image:
  repository: denol007/user-service
  tag: latest

service:
  port: 5000

env:
  PORT: "5000"
  SERVICE_NAME: "user-service"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/microservices"

fullnameOverride: "user-service"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
