apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipping-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Denol007/k8s.git
    targetRevision: HEAD
    path: helm/microservice
    helm:
      valueFiles:
        - ../../helm/values/shipping-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
